layer: None
set_name: 'user_tiny'
target_train: "data/meta/oi/user_tiny/target_train.csv"
pos_test: "data/meta/oi/user_tiny/target_test.csv"
neg_test: "data/meta/oi/user_tiny/extra.csv"
data:
  neg_train: "data/meta/oi/user_tiny/meta_neg.csv"
  pos_test: "data/meta/oi/user_tiny/target_test.csv"
  pos_train: "data/meta/oi/user_tiny/meta_pos.csv"
  neg_test: "data/meta/oi/user_tiny/extra.csv"
x: "ImageID"
y: "multi_label"
eqset: "AuthorProfileURL"
target_num_cls: 10
limit: 50
target: "data/model/oi/save/user_tiny/target/model.h5"
proxy: "data/model/oi/save/user_tiny/proxy/model.h5"

root: "data/raw/oi/user_tiny/"
meta_path: "data/meta/oi/oi_user_tiny.csv"
classifier: "simple"
use_y: False
feature: "histogram"
feat_args:
  bins:
    100
args: None

log: "log/res/oi/user_tiny/{}.csv"
meta_model: "data/model/oi/save/user_tiny/meta/{}_{}_{}.sav" # feat, set, layer

inspect_csv: "log/res/oi/user_tiny/d_inspect.csv"
e_inspect_csv: "log/res/oi/user_tiny/e_inspect_limit{}.csv"

log_cols:
  from_yaml:
    - "target"
    - "feature"
    - "layer"
    - "classifier"
  from_code:
    - "bag_size"
    - "best_score"
    - "params"
    - "report"
layer_dir: "data/meta/oi/user_tiny/{}"
layer_file: "/{}_{}.npy"
alpha: 5
layers_list:
  - 0
  - 49
  - 50
  - 51
  - 52
  - 120
  - 121
  - 122
  - 123
  - 146
  - 147
  - 148
  - 149
  - 154
  - 155

layer_shape:
  0:
    - 224
    - 224
    - 3
  49:
    - 28
    - 28
    - 192
  50:
    - 28
    - 28
    - 192
  51:
    - 28
    - 28
    - 32
  52:
    - 28
    - 28
    - 32
  120:
    - 7
    - 7
    - 576
  121:
    - 7
    - 7
    - 576
  122:
    - 7
    - 7
    - 576
  123:
    - 7
    - 7
    - 160
  146:
    - 7
    - 7
    - 960
  147:
    - 7
    - 7
    - 960
  148:
    - 7
    - 7
    - 960
  149:
    - 7
    - 7
    - 320
  154:
    - 1280
  155:
    - 10